name: portainer

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer-container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - default
      - outside

volumes:
  portainer_data:
    external: true
    name: portainer_data

networks:
  outside:
    external: true
    name: outside
